import { v4 as uuid } from 'uuid';
import type { Task } from './types';

export function seedIfEmpty() {
  if (localStorage.getItem('taskflow:tasks')) return;

  const now = new Date().toISOString();
  const today = now.slice(0, 10);
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
  const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10);

  const tasks: Task[] = [
    {
      id: uuid(),
      title: 'Review pull request for auth module',
      description: 'Check the new OAuth2 implementation before merging to main.',
      priority: 'high',
      status: 'pending',
      tags: ['work', 'code-review'],
      dueDate: today,
      estimateMinutes: 45,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Write weekly team update',
      description: 'Summarise sprint progress and blockers for the team channel.',
      priority: 'medium',
      status: 'pending',
      tags: ['work', 'writing'],
      dueDate: today,
      estimateMinutes: 20,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Morning stretches',
      description: '10 minutes of mobility work.',
      priority: 'low',
      status: 'pending',
      tags: ['health'],
      dueDate: today,
      recurrence: { freq: 'daily', interval: 1 },
      estimateMinutes: 10,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Read 30 pages of current book',
      priority: 'low',
      status: 'pending',
      tags: ['personal', 'reading'],
      dueDate: today,
      recurrence: { freq: 'daily', interval: 1 },
      estimateMinutes: 30,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Fix flaky test in CI pipeline',
      description: 'The integration test for the payments service times out ~30% of the time.',
      priority: 'high',
      status: 'pending',
      tags: ['work', 'devops'],
      dueDate: tomorrow,
      estimateMinutes: 90,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Grocery shopping',
      description: 'Vegetables, oat milk, coffee beans, sourdough.',
      priority: 'medium',
      status: 'pending',
      tags: ['personal', 'errands'],
      dueDate: tomorrow,
      estimateMinutes: 40,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Draft Q2 roadmap presentation',
      description: 'Slides for the all-hands. Cover goals, milestones, and risks.',
      priority: 'high',
      status: 'pending',
      tags: ['work', 'planning'],
      dueDate: nextWeek,
      estimateMinutes: 120,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Weekly team standup notes',
      priority: 'medium',
      status: 'pending',
      tags: ['work'],
      recurrence: { freq: 'weekly', interval: 1, daysOfWeek: [1, 3, 5] },
      estimateMinutes: 15,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Set up home lab NAS',
      description: 'Install TrueNAS, configure RAID, set up Plex.',
      priority: 'low',
      status: 'pending',
      tags: ['personal', 'tech'],
      estimateMinutes: 180,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Submit expense report',
      description: 'Conference flights and hotel from last month.',
      priority: 'high',
      status: 'completed',
      tags: ['work', 'admin'],
      dueDate: yesterday,
      completedAt: now,
      estimateMinutes: 15,
      createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
      updatedAt: now,
    },
    {
      id: uuid(),
      title: 'Upgrade Node.js to v22',
      description: 'Update all services, test locally, deploy to staging.',
      priority: 'medium',
      status: 'completed',
      tags: ['work', 'devops'],
      completedAt: new Date(Date.now() - 86400000).toISOString(),
      estimateMinutes: 60,
      createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
  ];

  localStorage.setItem('taskflow:tasks', JSON.stringify(tasks));
}
